### ISSUE TITLE
音频数据MD5值

### ISSUE THREAD

**Issue by MrShouxingMa** [ShenDezhou/icme2019#5]
您好！非常感谢您分享icme2019的比赛数据集，但看到数据集还有一个小疑惑？您上传了两个PDF文档，内含文件的MD5值，但好像少了音频数据的MD5值。请问是您漏传了还是本身就没有？期待您解答(因为官方已经关闭下载链接，所以来求助您)!

**Comment by ShenDezhou** [comment]
作者可能是抖音，过了太久，记不清细节了。
